# Generated by Django 5.2 on 2025-04-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_address_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivered', 'Delivered')], default='pickup', max_length=10),
        ),
    ]
