# Generated by Django 5.2 on 2025-04-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_delivery_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
