# Generated by Django 5.2 on 2025-05-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_options_remove_order_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='text_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
