# Generated by Django 5.2 on 2025-05-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude',
        ),
    ]
