# Generated by Django 5.2 on 2025-05-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_order_latitude_remove_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='units_per_case',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
