# Generated by Django 5.2 on 2025-05-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_order_is_completed_order_assigned_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude',
        ),
    ]
