# Generated by Django 5.2 on 2025-05-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_order_latitude_remove_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
